---
- name: Set SELinux to enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: Enable tomcat access
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  when: inventory_hostname | search("tomcat") 

- name: Enable http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  when: inventory_hostname | search("nginx") 
