---
- name: Set SELinux to enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: Create tomcat firewall service
  copy:
    src: tomcat.xml
    dest: /etc/firewalld/services/tomcat.xml
  when: inventory_hostname | search("tomcat")

- name: Reload firewalld
  systemd:
    state: restarted
    name: firewalld
  when: inventory_hostname | search("tomcat")

- name: Enable tomcat access
  firewalld:
    service: tomcat
    permanent: true
    state: enabled
  when: inventory_hostname | search("tomcat") 

- name: Enable http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  when: inventory_hostname | search("nginx") 
