---
- name: Create tomcat default folder
  file:
    path: /opt/tomcat/
    owner: tomcat
    group: tomcat
    state: directory
    mode: 0750

- name: Unpack tomcat tarball file
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.23/bin/apache-tomcat-8.5.23.tar.gz
    dest: /opt/tomcat/
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
    keep_newer: yes

- name: Configure server.xml to host a static content project
  lineinfile:
    path: /opt/tomcat/conf/server.xml
    insertafter: 'unpackWARs'
    line: '        <Context docBase="/opt/tomcat/characters" path="/characters" />'
